name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} enviroment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     python -m pip install -r requirements.txt
      - name: Python enviroment report
        run: |
          python -c "import sys; print(sys.version)"
          python -c "import platform; print(platform.platform())"
      - name: Black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
      - name: Flake8
        uses: py-actions/flake8@v2
        with:
          ignore: "F401,W503"
          max-line-length: "120"
          plugins: "flake8-bugbear flake8-black"
